name: example
description: "Template example app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  dart_wing:
    # When depending on this package from a real application you should use:
    #   url_launcher: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  package_info_plus: ^8.2.1
  easy_localization: ^3.0.7+1
  keycloak_wrapper: ^1.4.4
  sidebarx: ^0.17.1
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
